version: '3.7'

services:

  arbitrator:
    restart: on-failure:5
    ports:
      - '4767:4567'
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=wowvendor_galera
      - MARIADB_ROOT_PASSWORD=change-me
      - MARIADB_ADDRESSES=db1,db2
