services:

  arbitrator:
    restart: on-failure:5
    ports:
      - '4567:4567'
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - GALERA_CLUSTER_NAME=wowvendor_galera
      - MYSQL_ROOT_PASSWORD=change-me
      - MYSQL_ADDRESSES=db1,db2
      - PROVIDER_OPTIONS=
